print("*"*45)
print("*\t\t\t\t  *\t\t\t\t\t\t\t*")
print("*\t\t\\a\t\t  *\t\t  Bell (alert)\t\t*")
print("*\t\t\t\t  *\t\t\t\t\t\t\t*")
print("*"*45)
print("*\t\t\t\t  *\t\t\t\t\t\t\t*")
print("*\t\t\\b\t\t  *\t\t\tBackspace\t\t*")
print("*\t\t\t\t  *\t\t\t\t\t\t\t*")
print("*"*45)
print("*\t\t\t\t  *\t\t\t\t\t\t\t*")
print("*\t\t\\n\t\t  *\t\t\tNew line\t\t*")
print("*\t\t\t\t  *\t\t\t\t\t\t\t*")
print("*"*45)
print("*\t\t\t\t  *\t\t\t\t\t\t\t*")
print("*\t\t\\t\t\t  *\t\t Horizontal tab\t\t*")
print("*\t\t\t\t  *\t\t\t\t\t\t\t*")
print("*"*45)
print("*\t\t\t\t  *\t\t\t\t\t\t\t*")
print("*\t\t\\\\\t\t  *\t\t  Backslash \\\t\t*")
print("*\t\t\t\t  *\t\t\t\t\t\t\t*")
print("*"*45)
print("*\t\t\t\t  *\t\t\t\t\t\t\t*")
print("*\t\t\\\"\t\t  * Double quotation mark \" *")
print("*\t\t\t\t  *\t\t\t\t\t\t\t*")
print("*"*45)
print("*\t\t\t\t  *\t\t\t\t\t\t\t*")
print("*\t\t\\\"\t\t  * Single quotation mark \' *")
print("*\t\t\t\t  *\t\t\t\t\t\t\t*")
print("*"*45)
