print("*"*45)
print("*\t\t\t\t  *\t\t\t\t\t\t\t*\n*\t\t\\a\t\t  *\t\t  Bell (alert)\t\t*\n*\t\t\t\t  *\t\t\t\t\t\t\t*")
print("*"*45)
print("*\t\t\t\t  *\t\t\t\t\t\t\t*\n*\t\t\\b\t\t  *\t\t\tBackspace\t\t*\n*\t\t\t\t  *\t\t\t\t\t\t\t*")
print("*"*45)
print("*\t\t\t\t  *\t\t\t\t\t\t\t*\n*\t\t\\n\t\t  *\t\t\tNew line\t\t*\n*\t\t\t\t  *\t\t\t\t\t\t\t*")
print("*"*45)
print("*\t\t\t\t  *\t\t\t\t\t\t\t*\n*\t\t\\t\t\t  *\t\t Horizontal tab\t\t*\n*\t\t\t\t  *\t\t\t\t\t\t\t*")
print("*"*45)
print("*\t\t\t\t  *\t\t\t\t\t\t\t*\n*\t\t\\\\\t\t  *\t\t  Backslash \\\t\t*\n*\t\t\t\t  *\t\t\t\t\t\t\t*")
print("*"*45)
print("*\t\t\t\t  *\t\t\t\t\t\t\t*\n*\t\t\\\"\t\t  * Double quotation mark \" *\n*\t\t\t\t  *\t\t\t\t\t\t\t*")
print("*"*45)
print("*\t\t\t\t  *\t\t\t\t\t\t\t*\n*\t\t\\\"\t\t  * Single quotation mark \' *\n*\t\t\t\t  *\t\t\t\t\t\t\t*")
print("*"*45)
